### ISSUE TITLE
Needs more features to be added

### ISSUE THREAD

**Issue by suyashvinayakiya** [jonasbleyl/recurrence#45] opened 2016-08-18 12:20 UTC
There are many suggestion by me which you can add
1. syncing with Google Calendar
2.Exporting and Importing reminders of the app
3.Snooze option doesn't turn up in the notification even after switching it on(Issue)
4.Russian Language can be added
5.Time and location based reminder(ringing during that particular time)
6.Reminder doen't repeat next time (hour / day) most of the time(Issue)
7. Floating notification as Whatsapp if the screen is on

**Comment by jonasbleyl** [comment] 2016-08-18 19:57
* Syncing and location based reminders are on my TODO list already.
* Exporting and importing has already been added as an IAP on the play store version and won't be added to this one.
* Translations can be added on crowdin https://crowdin.com/project/recurrence

There have been no reports of snooze nor repeating reminders not working correctly so this would seem to be an issue on your end. I would need more information to be able to debug this.

As future reference, the issue is used to track issues. "Needs more features to be added" is not exactly a valid issue since you bundled multiple in once. This makes issues difficult to track and manage. Hence why I'll be closing this issue.

**Closed by jonasbleyl** 2016-08-18 19:57 UTC
